---
lightbox: true
editor: 
  markdown: 
    wrap: 72
---

# Einführung {#einfuehrung}

In diesem einführenden Kapitel wird zunächst anhand einer sog. Fachlandkarte auf das Themenfeld Sozialmanagement und Sozialwirtschaft eingegangen. Im Anschluss folgt ein Überblick zur Geschichte und statistischen Einordnung dieses Arbeitsfeldes bzw. gesellschaftlichen Sektors, den wir als Sozialwirtschaft bezeichnen. Außerdem müssen verschiedene Begriffsabgrenzungen vorgenommen werden, wie z. B. zwischen *Sozialmanagement* und *Non-Profit-Management* [vgl. z. B. @Wohrle2017], und auch muss darauf eingegangen werden, was Organisationen der Sozialwirtschaft von Non-Profit-Organisationen unterscheidet.

Das Sozialmanagement lässt sich anhand einer Fachlandkarte untergliedern. Eine Fachlandkarte wird in der Hochschuldidaktik genutzt, um komplexe Zusammenhänge übersichtlich darzustellen und um damit Lernenden in ein komplexes Arbeits-, Themen- und Forschungsfeld einzuführen [vgl. z. B. @Ritter-Mamczek2016]. Im Folgenden wird der Versuch unternommen, auf einer „Schatzkarte" die verschiedenen Provinzen des
[Sozialmanagements](https://de.wikipedia.org/wiki/Sozialmanagement "null") zusammenzufassen und zu entdecken (vgl. [Abb. 1.1](#figure11)).

![Abb. 1.1: Fachlandkarte Sozialmanagement [@Arnold2022a, [CC-BY
4.0](https://figshare.com/articles/figure/Social_Work_Management_Subject_Map/20151839?file=36033593)]](images/figure11.png){#figure1}

Im Bild ist das *Territorium der Grundlagen* zu sehen. Hier befinden wir uns an der Quelle der Sozialwirtschaft, d. h. es gilt die *sozialpolitischen* und *bildungspolitischen Rahmenbedingungen* und verschiedene *Managementkonzepte* kennenzulernen, wie soziale Organisation geleitet, geführt und gestaltet werden können. Links oben im Bild ist die Höhle der *Finanzbuchhaltung* zu sehen, die sich mit der Verwaltung der verfügbaren Finanzmittel beschäftigt. Im Wald der *Kosten- und Leistungsrechnung* können wir uns zudem einen Überblick
darüber verschaffen, wie wirtschaftlich unsere Organisation arbeitet.

Darüber hinaus ist in der Mitte des Bilds die Provinz der Organisation zu erkennen. Man braucht ein grundlegendes Wissen über die Organisationstheorie, z. B. darüber wie *Organisationen in der Sozialwirtschaft* aufgebaut sind, wie sie finanziert werden und wie sie letztlich funktionieren. Dann gibt es die Provinz der Finanzen, wo es neben der Kosten- und Leistungsrechnung und Buchführung um die Frage der *Finanzierung* geht. In diesem Zusammenhang muss ein Überblick über die verschiedenen Finanzquellen gewonnen werden (wie z. B. Leistungsentgelte oder Spenden). Schließlich gibt es noch am linken Rand die Provinz des
*Leaderships*, wo man sich u. a. die Frage stellt, was adäquate Mittel, Werkzeuge und Instrumente darstellen, um Führung und Personalentwicklung innerhalb sozialer Organisationen zu gestalten.

An den Rändern der Karte sehen wir links unten das *Social Entrepreneurship* und die Insel des *Sozio-Marketings*. Dort sind alle Aufgaben- und Themenstellungen versammelt, die sich mit der Unternehmensgründung bzw. dem Marketing beschäftigen. Darüber hinaus ist am rechten oberen Rand der Landkarte der Ozean der Strategie abgebildet. Im Rahmen des Sozialmanagements muss sich daher auch mit den verschiedenen Aspekte und *Grundlagen des strategischen Managements* auseinandergesetzt werden, z. B. wie man Organisationen langfristig leiten, gestalten und steuern kann. In der Bucht des *Controllings* kann man sich sprichwörtlich an den Strand setzen, wo man sich das *Projekt- und Netzwerkmanagement* zu Gemüte führen kann, was natürlich auch eine wesentliche Grundkompetenz dafür darstellt, um in sozialen Organisationen zu arbeiten.

Kurzum sind in dieser Fachlandkarte verschiedene Arbeits- und Themenfelder zu finden, die in diesem Grundlagenlehrbuch vorgestellt und vertieft werden. Der Fokus dieses OER Textbuchs liegt allerdings auf einer Einführung in die sozial- und betriebswirtschaftlichen Grundlagen,
dem organisationsbezogenen Management sowie den Managementansätzen für das Sozialmanagement liegen.[^1_einfuehrung-1]

[^1_einfuehrung-1]: Für eine ausführliche Darstellung der wichtigsten     Entwicklungsschritte vgl. z. B..Wöhrle, A. (2011). Sozialwirtschaft. In H. Thiersch, & H. U. Otto (2011), *Handbuch Soziale Arbeit*. *Grundlagen der Sozialarbeit und Sozialpädagogik* (S. 1562-1570, 5. Aufl.). München: Ernst Reinhardt. https://doi.org/10.2378/ot4a.art145

## Geschichte der Sozialwirtschaft {#geschichte}

### Die Anfänge der Sozialwirtschaft[^1_einfuehrung-2] {#die-anfaenge-der-sozialwirtschaft}

[^1_einfuehrung-2]: Für eine ausführliche Darstellung der wichtigsten Entwicklungsschritte vgl. z. B..Wöhrle, A. (2011). Sozialwirtschaft. In H. Thiersch, & H. U. Otto (2011), *Handbuch Soziale Arbeit*. *Grundlagen der Sozialarbeit und Sozialpädagogik* (S. 1562-1570, 5. Aufl.). München: Ernst Reinhardt. https://doi.org/10.2378/ot4a.art145

Ein Ausflug in die Geschichte des Sozialmanagements bzw. der Sozialwirtschaft ist notwendig, nicht nur um zu verstehen, wie sich alles entwickelt hat, sondern auch um viele der aktuell diskutierten Fragen rund um den Sozialstaat besser nachvollziehen zu können. Wir beginnen in der Neuzeit, insbesondere in Frankreich, mit der ersten Erwähnung bzw. der ersten theoretischen Auseinandersetzung mit sozialwirtschaftlichen Grundlagen, wie z. B. der [katholischen Soziallehre](https://de.wikipedia.org/wiki/Katholische_Soziallehre "null").
In den [päpstlichen Sozialenzykliken](https://de.wikipedia.org/wiki/Sozialenzyklika "null") wurden bspw. Gedanken entwickelt, die später in Form des rechtlich verbindlichen
[Subsidiaritätsprinzips](https://www.bpb.de/kurz-knapp/lexika/pocket-europa/16951/subsidiaritaetsprinzip/ "null") weiterentwickelt wurden und mittlerweile die Rahmenbedingungen für viele
entwickelten Sozialökonomien (wie z. B. für die deutsche [Soziale Marktwirtschaft](https://www.bpb.de/kurz-knapp/lexika/lexikon-der-wirtschaft/20642/soziale-marktwirtschaft/ "null")) darstellen. Zur etwa gleichen Zeit ist [Léon Walras](https://de.wikipedia.org/wiki/L%C3%A9on_Walras "null") im Rahmen seiner [allgemeinen
Gleichgewichtstheorie](https://de.wikipedia.org/wiki/Walrasianisches_allgemeines_Gleichgewichtsmodell "null") der Frage nachgegangen, wie Grund und Boden denn verstaatlicht werden können. Wenn mit einer Verstaatlichung zwar Steuern vermieden werden, so könnte seiner Meinung nach doch zumindest die Produktion gesteigert werden. Dies soll und kann an dieser Stelle keine vollständige Darstellung der geschichtlichen Grundlagen darstellen. Wir wollen es bei diesen Beispielen belassen. Festzuhalten ist aber, dass all diese verschiedene Grundlagen das „soziale Wirtschaften" [vgl. z. B. @Beck2013] in unseren heutigen (post-)modernen Gesellschaften zu beschreiben und zu verstehen verhelfen.

### Gründung von Genossenschaften, Diakonie und die Bismarck'schen Gesetze {#gruendung}

Wenig später ist es zur Etablierung bzw. Entwicklung des Genossenschaftswesens gekommen.
[Genossenschaften](https://de.wikipedia.org/wiki/Genossenschaft "null") waren ursprünglich nicht *per se* als sozial-gemeinnützige Einrichtungen ins Leben gerufen, sondern sind vielmehr dafür gegründet worden, einen Zusammenschluss oder Verbund von Personen und Einrichtungen zur wirtschaftlichen und/oder sozialen Förderung ihrer Mitglieder ins Leben zu rufen, z. B. wie Raiffeisen für hilfsbedürftige Landarbeiter oder die Volksbanken im Bankenwesen. In diesem Zusammenhang wurden wichtige Prinzipien entwickelt, wie z. B. die Selbstverantwortung, Selbsthilfe und Selbstverwaltung innerhalb von Genossenschaften, die in den letzten Jahren wieder verstärkt in der Organisationsforschung diskutiert wurden. Später kam es dann insbesondere im Bereich der konfessionellen Trägerschaften im [Diakonie](https://www.diakonie.de/ "null")- und [Caritaswesen](https://www.caritas.de/ "null") zur Gründung von Einrichtungen, die sich speziell um die Notlagen von Menschen gekümmert haben. Beispielhaft sei hier die Gründung der ersten Stadtmission in Deutschland von [Johann Hinrich Wichern](https://de.wikipedia.org/wiki/Johann_Hinrich_Wichern "null") in Hamburg genannt. Es sollte nicht unerwähnt bleiben, dass am Ende des 19. Jahrhunderts die [Bismarcksche Sozialgesetze](https://www.bpb.de/themen/soziale-lage/rentenpolitik/289619/bismarcks-sozialgesetze/ "null") eine Innovation des sozialstaatlichen Denkens darstellte und ein
wichtiges Fundament für das [Sozialversicherungswesen](https://de.wikipedia.org/wiki/Sozialversicherung "null") und die Etablierung bzw. Festsetzung des [Solidarprinzips](https://www.bpb.de/themen/gesundheit/gesundheitspolitik/252319/das-solidarprinzip/ "null") bildete.

### Paradigmenwechsel in der Finanzierung der Sozialwirtschaft {#paradigmenwechsel}

Im 20. Jahrhundert stand lange Zeit zunächst das Prinzip der Vollkostendeckung bzw. „Selbstkostendeckung" [@Mross2017] im Vordergrund, d. h. alle Einrichtungen, die [gemeinnützigeZwecke](https://www.gesetze-im-internet.de/ao_1977/__52.html#:~:text=(1)%20Eine%20K%C3%B6rperschaft%20verfolgt%20gemeinn%C3%BCtzige,sittlichem%20Gebiet%20selbstlos%20zu%20f%C3%B6rdern. "null") verfolgt haben und als [Leistungserbringer](https://de.wikipedia.org/wiki/Leistungserbringer "null") aufgetreten sind, haben sämtliche notwendigen finanziellen Mittel vom Staat vollständig refinanziert bekommen. Mitte der 1970er Jahre ist aus der Kritik am „Versorgungs- oder Wohlfahrtsstaat" das Anliegen entstanden, dass man insbesondere diesen Bereich der Sozialwirtschaft und letztlich auch das Sozialmanagement stärker professionalisieren sollte.

### Etablierung der ersten Studiengänge an Fachhochschulen {#fachhochschulen}

In dieser Zeit etablierten sich die ersten Studiengänge der Sozialen Arbeit an den Fachhochschulen, die sich vereinzelt auch mit dem Thema auseinandergesetzt haben, wie man das Management von sozialen Organisationen gestalten könnte. In den 1980er Jahren kam es schließlich zu einer Etablierung von Studiengängen, die sich mit dem Sozialmanagement oder dem Management sozialer und Non-Profit-Einrichtungen beschäftigten. Es wurden hauptsächlich zunächst Diplomstudiengängen und später (mit dem [Bologna-Reformprozess](https://de.wikipedia.org/wiki/Bologna-Prozess "null")) auch Bachelor- und Masterstudiengänge entwickelt, die sich mit dem Thema auseinandergesetzt und versucht haben, einerseits das sozialpädagogische und sozialarbeiterische Wissensspektrum und andererseits das betriebswirtschaftliche Wissen zu vermitteln und weiterzuentwickeln. Seit den 2000er Jahren haben sich dann verschiedene Studiengänge insbesondere im Bereich des Sozialmanagements, der Sozialwirtschaftslehre und im Non-Proﬁt-Management etabliert, die unterschiedliche Schwerpunktsetzungen haben und aktuelle Themen und Aufgaben des Sozialmanagements behandeln. Heute gibt es eine kaum noch überschaubare Vielzahl und Vielfalt an Studiengängen, die sich mit dem Management von sozialen Organisationen und dem Management in der Sozialwirtschaft beschäftigen [vgl. z. B. den Studienführer von @Boessenecker2014].

### Das neue Steuerungsmodell {#steuerungsmodell}

Mit dem ökonomischen Denken in den 1990er Jahren fand schließlich ein Umdenken statt, was die Finanzierung der Sozialwirtschaft betraf. Das ursprüngliche Kostendeckungsprinzip wurde abgelöst durch ein neues Prinzip, nämlich das „[Neue Steuerungsmodell (NSM)](https://de.wikipedia.org/wiki/Neues_Steuerungsmodell "null")". Darauf muss später noch genauer eingegangen werden. Nach diesem Modell soll ein Wettbewerb um die öffentlichen Leistungen generiert werden, wobei Mittel nicht nach dem „Gießkannenprinzip" ausgeteilt werden. Vielmehr soll es stets bedarfsbezogen und auch im Sinne der Sozialraumorientierung eine Gewichtung geben, in welchen Stadtteilen beispielsweise bestimmte Förderungen in welchem Umfang fließen.

### Soziales Unternehmertum {#unternehmertum}

Seit den 1960er Jahre hat man sich auch auf europäischer Ebene stärker mit sozialpolitischen Themen auseinandersetzen müssen und eine [Europäische Sozialcharta](https://www.sozialcharta.eu/ "null") (am 26. Februar 1965 in Kraft getreten) entwickelt, in der festgehalten ist, welchen Aufgabenstellungen denn ein Sozialstaat nachzukommen hat. Das Thema des sozialen Unternehmertums bzw. Social Entrepreneurship ist dann 2011 und 2014 mit verschiedenen Initiativen auf europäischer Ebene aufgegriffen worden [vgl. z. B. die Social Business Initiative in @Europeancommission2015social].

## Sozialwirtschaft in Deutschland und Europa {#deutschland}

### Gesamtwirtschaftliche Einordnung {#gesamtwirtschaft}

Um die Sozialwirtschaft besser in das gesamte Wirtschaftssystem einordnen zu können, ist ein quantitativer Überblick notwendig. In einer Untersuchung des Instituts der deutschen Wirtschaft Köln aus dem Jahr [@IDW2004wohlfahrtsverbaende] wurden die verschiedenen „Sozialmultis" dargestellt (vgl. [Abb. 1.2](#figure12)). Dabei handelt es sich um die verschiedenen Wohlfahrtsverbände.

![Abb. 1.2: Sozialunternehmen und Beschäftigte in der Sozialwirtschaft
[@IDW2004wohlfahrtsverbaende, S. 9,
[Link](https://www.yumpu.com/de/document/view/7199735/auf-den-schultern-der-schwachen)]](images/figure12.png){#figure12}

Man kann deutlich erkennen, dass die konfessionellen Träger wie der Caritasverband und auch das Diakonische Werk sowohl die meisten Einrichtungen betreiben als auch die meisten Mitarbeitenden haben. Darüber hinaus sind natürlich auch die anderen größeren Wohlfahrtsverbände zu nennen, wie der Paritätische Verband, die Arbeiterwohlfahrt und das Deutsche Rote Kreuz. Alle gemeinsam beschäftigten im Jahre 2020 etwa rund 1,3 Millionen Menschen. Von den Sozialmultis werden bundesweit ungefähr 100.000 Einrichtungen betrieben.
Wenn man die Träger der freien gemeinnützigen Wohlfahrtspflege hinzunimmt, macht das ungefähr 5% der gesamtwirtschaftlichen Leistung aus. Wir haben ungefähr 43 Millionen Erwerbstätige in Deutschland [z. B. @Beck2013]. In einem Gutachten zur Sozialwirtschaft in Sachsen unter besonderer Berücksichtigung der Freien Wohlfahrtspflege vom [Gesundheitsökonomischen Zentrum an der TU Dresden](https://tu-dresden.de/bu/wirtschaft/wwsprofecon/ressourcen/dateien/publikationen/Sozialwirtschaft_2011.pdf?lang=de "null") wurde berechnet, dass in Sachsen der Anteil des Bereichs der „freigemeinnützigen Wohlfahrtspflege" an der Bruttowertschöpfung bei ungefähr 7,15% liegt (Bundesdurchschnitt: 6,74%) [@Karmann2011gutachten].

Im Jahr 2008 gab es in Deutschland ca. 2,5 Millionen Mitarbeitende in der Sozial- und Gesundheitswirtschaft (es wird hier der Gesundheitsbereich hinzugerechnet) und auf europäischer Ebene rechnen wir etwa mit 11 Millionen Mitarbeitenden in den genannten Bereichen ([@Beck2013]). Wenn man dann die Wirtschaftsleistung in der Europäischen Union betrachtet und den öffentlichen Sektor herausrechnet,
dann machen Unternehmen der Sozialwirtschaft ungefähr 10% der Bruttowertschöpfung aus, die eben nur der Sozialwirtschaft zugeordnet werden können und das Gesundheitswesen ist hier in dem Fall nicht mitgezählt [@Beck2013].

### Beschäftigungszahlen {#beschaeftigungszahlen}

Gehen wir einmal noch auf eine andere Statistik ein, und zwar auf die Beschäftigungszahlen in der Sozial- und Gesundheitswirtschaft. Hier sind die Zahlen von 2014 und 2020 gegenübergestellt, die sich in den jeweiligen Jahresberichten der Bundesagentur für Arbeit [@Bundesagentur2014beschaeftigte] zum Juli des Jahres (saisonbereinigt) finden. Im Bereich Erziehung und Unterricht sind im Jahr 2014 1.164.300 sozialversicherungspflichtig Beschäftigte angestellt gewesen. In 2020 waren bereits rund 1.347.000 Angestellte beschäftigt (15%ige Steigerung). In einem ähnlichen Umfang ist auch das Beschäftigungswachstum im Bereich Gesundheitswesen auf 2.585.000 (+13,0%) und im Bereich Heime und Sozialwesen auf 2.474.000 (+20,6%) gestiegen. Diese Zahlen bieten eine kurze Einordnung der Sozialwirtschaft. Im Verhältnis dazu können wir von ungefähr 43 Millionen Erwerbstätigen in allen Branchen ausgehen.

### Finanzierungsmix für Träger der freien Wohlfahrtspflege {#finanzierungsmix}

Wenn wir auf die Einnahmenseite blicken und die Frage stellen, wie denn die freie Wohlfahrtspflege finanziert wird, dann wird deutlich, dass es einen grundsätzlichen Mix aus unterschiedlichen Finanzierungsquellen gibt (vgl. dazu [Abb. 1.3](#figure13)).

![Abb. 1.3: Finanzierung der freien Wohlfahrtspflege [@IDW2004wohlfahrtsverbaende, S. 29,
[Link](https://www.yumpu.com/de/document/view/7199735/auf-den-schultern-der-schwachen)]](images/figure13.png){#figure13}

Nach einer Untersuchung des Instituts der deutschen Wirtschaft Köln [@IDW2004wohlfahrtsverbaende] bestreiten zu 69% freie Träger ihr Einkommen aus den Leistungsentgelten. Leistungsentgelte sind öffentliche Zuwendungen bzw.
öffentliche Mittel, wie z. B. abgerechnete Pauschalen, geleistete Fachleistungsstunden oder auch Tagessätze. Darüber hinaus gibt es öffentliche Zuwendungen, z. B. im Rahmen von Projekten oder institutionellen Finanzierungen. Die konfessionellen Träger finanzieren sich teilweise noch aus kirchlichen Zuwendungen. Schließlich gibt es noch eine Reihe von sonstigen Quellen, wie z. B. Projektmittel, Spenden und Beiträge. Beiträge gibt es in gemeinnützigen Einrichtungen und Organisationen, die Mitglieder haben, wie z. B. Vereine oder Genossenschaften. Dazu zählen auch Elternbeiträge in der Kita. Was man hier deutlich sieht -- und das ist gleichzeitig ein Markenzeichen für die Sozialwirtschaft -- ist, dass wir es grundsätzlich mit unterschiedlichen Finanzierungsquellen zu tun haben. Zum Erfolg einer Einrichtung bzw. zu deren Gesamtfinanzierung reichen eben öffentliche Mittel, die für die Finanzierung von Leistungen benötigt werden, nicht zwingend aus. Vielmehr müssen wir uns Gedanken darüber machen, wie wir den restlichen Betrag refinanzieren können, der nicht auf öffentlichen, sondern dann aus privaten bzw. Eigenmitteln oder aus Beiträgen und Spenden finanziert werden muss.

## Non-Profit-Organisationen {#npo-organisationen}

### Begriff Non-Profit-Organisationen {#begriffnpo}

Im Folgenden wird näher darauf eingegangen, was Non-Profit-Organisationen ausmacht. Konkret handelt es sich dabei um 
> „alle diejenigen Organisationen, die weder erwerbswirtschaftliche Firmen noch öffentliche Behörden der unmittelbaren Staats- und Kommunalverwaltung sind. NPO sind ferner jene Organisationen, die einem gesellschaftlich als sinnvoll und notwendig anerkannten Leistungsauftrag folgen und dabei nicht in erster Linie vom Ziel der Gewinngenerierung geleitet werden. Nonprofit-Organisationen werden dabei gemeinhin als Teil des sogenannten „Dritten Sektors" verstanden, der neben bzw. zwischen den beiden idealtypischen ‚Polen' Markt und Staat angesiedelt ist" [@helmig2019nonprofit].

Demzufolge sind Non-Profit-Organisationen also solche Organisationen, die nicht zum Staat und nicht zum Wirtschaftssektor gehören und gewissermaßen den dritten Sektor in der Gesellschaft bilden. Sie verfolgen keine Gewinnmaximierungsziele, sondern gehen einem öffentlichen anerkannten bzw. gesetzlich geregelten Auftrag nach (siehe [Tab. 1](#table1)).

| **Organisationsbereiche (nach Funktionen)** | **Typen von Organisationen**                                       |
|---------------------------------------------|----------------------------------------------------------------------|
| **Wirtschaftliche Organisationen**          | Wirtschafts- und Arbeitgeberverbände  |
|                                             | Gewerkschaften                        |
|                                             | Berufsverbände                        |
|                                             | Verbraucherorganisationen             |
| **Soziokulturelle Organisationen**          | Sportorganisationen                                               |
|                                             | Freizeitvereine                                                   |
|                                             | Heimatvereine                                                     |
|                                             | Diverse Kirchen, Sekten                                           |
|                                             | Organisationen in den Bereichen von Kunst und Kultur, von         |
|                                             |   Wissenschaft und Forschung und von Bildung und Erziehung          |
|                                             | Organisationen zur Gestaltung der Lebenswelt (Wohnumfeld,         |
|                                             |   Nachbarschaft etc.)                                               |
| **Politische Organisationen**               | Politische Parteien                                               |
|                                             | Natur- und Umweltorganisationen                                   |
|                                             | Politisch orientierte Organisationen                              |
|                                             | Organisierte Bürgerinitiativen                                    |
| **Karitative Organisationen**               | Hilfsorganisationen für bestimmte Bevölkerungskreise (Betagte,    |
|                                             | Behinderte, Kranke, Süchtige, Benachteiligte, Geschädigte);       |
|                                             |   Wohlfahrtsverbände und deren Einrichtungen                        |
|                                             | Entwicklungshilfeorganisationen                                   |
|                                             | Organisierte Selbsthilfegruppen mit karitativen Zwecken           |


Tab. 1: Typen privater Non-Profit-Organisationen [@Schwarz1986management, S. 7]{#table1}

Auf die Frage, welche Arten von Non-Profit-Organisationen existieren,
gibt die folgende Abbildung einige Anhaltspunkte:

-   *Wirtschaftliche Organisationen* wie z. B. Gewerkschaften,
    Arbeitgeberverbände und Verbraucherorganisationen;

<!-- -->

-   *Soziokulturelle Organisationen* wie z. B. Sportvereine,
    Organisation für Kunst und Kultur sowie wissenschaftliche
    Einrichtungen;

-   *Politische Organisationen* wie z. B. Parteien, Umweltbewegungen,
    Umweltverbände;

-   *Karitative Organisationen*, die sich um die Hilfe für Menschen in
    besonderen Lebenslagen kümmern, wie z. B. Wohlfahrtsverbände und
    Entwicklungshilfeorganisationen.

Non-Profit-Organisation sind demzufolge alle Organisationen in der
Gesellschaft, die prinzipiell gemeinnützige Zwecke, aber darüber hinaus
auch wirtschaftliche Zwecke verfolgen können, aber nicht zwingend auf
eine Gewinnmaximierung aus sind. Wenn wir demgegenüber von der
Sozialwirtschaft reden, müssen wir noch eine Einschränkung vornehmen. Es
gibt zwar viele Organisationen, die hier in die Kategorie
Soziokulturelle Organisationen fallen, z. B. Organisationen zur
Förderung von Kultur oder Bildung und Erziehung. Hinzugezählt werden
müssen auch diejenigen Organisationen, die der Gestaltung des
Lebensumfeldes dienen, und auch karitative Organisationen, also alle
Wohlfahrtsverbände, Hilfsorganisationen und freigemeinnützige
Einrichtungen. Nichtsdestotrotz gibt es auch Graubereiche: Soziale
Organisationen, also spezifische Non-Profit-Organisationen; der Begriff
muss später noch näher bestimmt werden.

### Gemeinsamkeiten und Unterschiede zwischen Profit- und Non-Profit-Organisationen {#vergleichnpo}

Zur genaueren Differenzierung von Non-Profit-Organisationen und
erwerbswirtschaftlichen Organisationen ist folgende [Abb.
1.4](#figure14) hilfreich [@Schwarz1986management, S. 8].

<!-- ![Abb. 4: Finanzierung der freien Wohlfahrtspflege Gemeinsamkeiten und Unterschiede zwischen NPO und Unternehmen nach [@Schwarz1986management, S. 8]](images/figure4.png){#figure4} -->

![Abb. 1.4: Gemeinsamkeiten und Unterschiede zwischen NPO und Unternehmen [nach @Schwarz1986management, S. 8]](images/figure14.png){#figure14}

#### Gemeinsamkeiten {#npogemeinsamkeiten}

Nach @Schwarz1986management bestehen alle Organisationen, egal ob sie erwerbswirtschaftliche (For-Profit) oder nicht-erwerbswirtschaftliche (Non-Profit) Unternehmen darstellen, aus verschiedenen Teilsystemen. Organisationen sind immer zugleich zielgerichtete Systeme, produktive Systeme und soziale Systeme. Damit ist gemeint, dass jede Organisation immer zu einem konkreten Zweck gegründet wurde, der -- wenn vorhanden -- in der Satzung bzw. im Gesellschaftervertrag der gegründeten Einrichtung
niedergeschrieben ist, und der die Grundlage bildet für das gesamte Arbeiten in der Organisation. Darüber hinaus sind alle diese Organisationen auch produktive Systeme, d. h. hier geht es um die Frage, wie ist der Personaleinsatz in der Einrichtung organisiert, welche finanziellen Ressourcen stehen zur Verfügung, wie kann man neue Finanzierungsquellen aufschließen und wie werden Produkte und Dienstleistungen angeboten. Darüber hinaus sind alle Organisationen auch soziale Systeme. Es gilt immer mit zu bedenken, wie Mitarbeitende motiviert und dabei unterstützt werden können, ihre Kompetenzen weiterzuentwickeln. Im Vordergrund des sozialen Systems steht also der Faktor „Humankapital"

Alle Organisationen, sind sie denn einmal gegründet, müssen sich damit auseinandersetzen, wie das Management ihrer Einrichtung zu funktionieren hat, also welche Führungsprozesse zu organisieren sind, wie Ziele gesetzt werden, wie geplant wird, wie etwa Personalplanung stattfindet und wie Koordinierung und Organisationen im engeren Sinne in der Einrichtung umgesetzt werden kann. All das sind Aufgaben, die jede Einrichtung zu erfüllen hat. Kurz zusammengefasst: Auch Non-Profit-Organisationen müssen sich mit dem Management, also mit ökonomischen Fragestellungen auseinandersetzen und haben ähnliche
Rahmenbedingungen zu beachten wie auch erwerbswirtschaftliche
Organisationen bzw. umgekehrt.

#### Unterschiede {#npounterschiede}

Und man kann neben den Gemeinsamkeiten auch verschiedene Unterschiede
herausarbeiten, auch das geht hier auf eine Untersuchung von Schwarz
@Schwarz1986management zurück (vgl. [Tab. 2](#table2)).

| **Strukturmerkmale**             | **For-Profit Unternehmen**                    | **Non-Profit Organisationen**                               |
|----------------------------------|-----------------------------------------------|-------------------------------------------------------------|
| **Hauptzweck**                   | Erwirtschaftung eines möglichst hohen Ertrags auf das investierte Kapital für Eigentümer (Formalziele: Gewinn und Rentabilität) – Erwerbswirtschaft | Erbringung von Leistungen für bestimmten Personenkreis in der Sozial- und Gesundheitswirtschaft (Sachziel: satzungsgemäße Zwecke) – Bedarfswirtschaft |
| **Adressaten und Marktbeziehung**| Deckung des Fremdbedarfs von Nachfrage durch Angebot auf Märkten | Deckung des Eigenbedarfs von Mitgliedern, Klienten etc. und des gesellschaftlichen Bedarfs (Identitätsprinzip: Mitglied = Kunde) |
| **Steuerungsprinzipien**         | Marktorientierung, Ausrichtung an Kunden- und Wettbewerberverhalten | Marktsteuerung teils nicht existent, teils sekundär; Mitglieder bestimmen demokratisch (direkt) oder durch indirektes Verhalten über Leistung (Versorgungs- und Bedarfsorientierung) |
| **Güter und Dienstleistungen**   | Nur private marktfähige Individualgüter, die ausschließlich vom einzelnen Käufer genutzt werden können | Kollektivgüter, die einer ganzen Gruppe zugutekommen, auch denjenigen, die nicht dafür zahlen können; hauptsächlich Dienstleistungen |
| **Finanzmittel**                 | Kapitalanlagen und Umsatzerlöse               | Mitgliedsbeiträge, Leistungsentgelte, Spenden, Steuervergünstigungen etc. |

Tab. 2: Unterscheidung von Unternehmen der Erwerbswirtschaft und
Non-Profit-Organisationen [@Schwarz1986management]{#table2}

Der Hauptzweck von Non-Profit-Organisationen ist insbesondere, dass hier
Leistungen für einen ganz bestimmten Personenkreis der Sozial- und
Gesundheitswirtschaft erbracht werden. Man spricht in diesem
Zusammenhang auch von einer Bedarfswirtschaft, d. h. es wird immer
anhand von gesetzlichen Rahmenbedingungen bzw. den Bedürfnissen der
jeweiligen Zielgruppe aus geplant, während die Erwerbswirtschaft stärker
den Blick darauf richtet, das eingesetzte Kapital und den Ertrag zu
steigern. In der Erwerbswirtschaft steht daher der Gewinn und die
Rentabilität im Blick als Formalziele im Vordergrund. Profitorientierte
Organisationen haben die Nachfrage und das Angebot auf Märkten im Blick,
während Non-Profit-Organisationen den Eigenbedarf ihrer Mitglieder,
Klient\*innen bzw. allgemein den gesellschaftlichen Bedarf
berücksichtigen müssen. Man spricht in letzterem Fall von sozialen
Märkten bzw. vom Gesundheitsmarkt, was einen abgegrenzten Bereich
darstellt.

Ebenso unterscheiden sich die Steuerungsprinzipien zwischen Profit- und
Non-Profit-Bereich. Die Erwerbswirtschaft orientiert sich am Markt und
richtet ihre Produkte und Dienstleistungen an den möglichen
Entwicklungen im Markt aus. Dabei müssen Wettbewerb, Kundenorientierung
und das Verhalten der Wettbewerber und Kunden ständig analysiert werden,
während es bei den Non-Profit-Organisationen eher darum geht, dass
Mitglieder mitbestimmen können, wie die Einrichtungen sich entwickeln
und auch, dass insbesondere die Perspektiven der Klient\*innen in den
Mittelpunkt geschoben werden. Die angebotenen Güter und Dienstleistungen
unterscheiden sich zwischen Profit- und Non-Profit-Organisationen.
Profitorientierte Organisationen setzen die auf Märkten gehandelte
Individualgüter ab. Es kann natürlich auch Produktionsgüter geben.
@Schwarz1986management sagt, dass Non-Profit-Organisationen
tendenziell eher Kollektivgüter produzieren, mit anderen Worten also
soziale Dienstleistungen anbieten. Auch hinsichtlich der Finanzmittel
gibt es Unterschiede. Profitorientierte Organisation können
beispielsweise Geld am Kapitalmarkt anlegen und finanzieren sich aus
Umsatzerlösen. Bei den Non-Profit-Organisationen existieren verschiedene
Einnahmequellen, wie z. B. Leistungsentgelte, öffentliche Zuwendungen,
Mitgliederbeiträge oder Spenden.\
\
Abschließend muss der hier nach @Schwarz1986management vorgestellte
Ansatz noch einmal kritisch betrachtet werden. Diese Übersicht ist
natürlich eine Vereinfachung, um wesentliche Unterschiede zwischen
diesen Typen von Unternehmen herauszuarbeiten. Die Übersicht stammt auch
aus den 1980er Jahren und wurde in verschiedenen Lehrbüchern immer
wieder reproduziert. Daher nehmen wir hier auch Bezug darauf. Beachtet
werden muss allerdings, dass sich die Grenzen zwischen Profit- und
Non-Profit-Organisationen über die letzten Jahre hinweg verschoben
haben. Selbstverständlich gibt es auch Grenzbereiche bzw. eine Grauzone.
So gibt es natürlich auch viele Non-Profit-Organisationen, die neben
ihrer gemeinnützigen Arbeit auch noch einen wirtschaftlichen
Geschäftsbetrieb besitzen und dort eine Gewinnmaximierung verfolgen
können. Genauso gibt es auch For-Profit-Organisationen, die im Bereich
der Sozialwirtschaft tätig sind, wie z. B. Pflegeeinrichtungen für
einkommensstärkere Bevölkerungsgruppen, die durch Eigen- bzw.
Selbstbeiträge andere und umfangreichere Dienstleistungen (über den
gesetzlichen Anspruch hinaus) beanspruchen können. All das sind
sozusagen auch erwerbswirtschaftliche Sichtweisen bzw. Elemente, die
auch in der Sozialwirtschaft immer mehr an Bedeutung gewinnen. Das
bringt uns zu dem Punkt, dass wir bei der Unterscheidung von For-Profit-
und Non-Profit-Organisationen von einem breiten Spektrum ausgehen
müssen. Auf der anderen Seite des Spektrums stehen idealtypisch die
For-Profit-Organisationen, auf der anderen Seite die
Non-Profit-Organisationen. In der Realität befinden wir uns
möglicherweise immer zwischen diesen verschiedenen Idealtypen. Im
Folgenden werden wir demnach Organisationen in den Blick nehmen, die
„tendenziell" Non-Profit-Organisationen darstellen und die im erwähnten
Spannungsfeld zwischen diesen beiden Polen stehen.

## Begriff Soziale Organisation {#begriff-soziale-organisation}

In Abgrenzung zum Begriff Non-Profit-Organisation wird nunmehr noch eine
Abgrenzung zu dem der „Sozialen Organisation" notwendig. Die Merkmale
von Sozialen Organisationen lassen sich wie in der folgenden Liste
versuchen festzumachen:

-   Soziale Einrichtungen sind insbesondere Unternehmen, die
    Sozialdienstleistungen erbringen und/oder Güter und Dienstleistungen
    für besonders schutzbedürftige Bevölkerungsgruppen und entsprechend
    gesetzlicher Aufträge (z. B. Erziehung, Betreuung, Lernen) anbieten.
    Diese Sozialunternehmen streben im Rahmen der Produktion von Waren
    bzw. bei der Erbringung von Dienstleistungen ein soziales Ziel an.

-   Sie zielen im Sinne der Gemeinnützigkeit auf eine Bedarfs- und
    Kostendeckung anstatt auf Gewinnmaximierung. Nichtsdestotrotz müssen
    auch soziale Einrichtungen Gewinne erwirtschaften, d. h. am Ende des
    Jahres muss etwas überbleiben. Dieser Überschuss muss allerdings
    wieder dem Einrichtungszweck zugutekommen. Die Gemeinnützigkeit ist
    in der Abgabenordnung geregelt, nach der der Gesetzgeber den als
    gemeinnützig anerkannten Einrichtungen
    Steuerermäßigungen/-befreiungen einräumt, wie z. B. für
    Ertragsteuern, Umsatzsteuer etc.

-   Sie offerieren „soziale personenbezogene Dienstleistungen"
    [@Klatetzki2010], die sich aus gesetzlich normierten
    Aufträgen (z. B.
    [SGB](https://www.bpb.de/kurz-knapp/lexika/politiklexikon/18231/sozialgesetzbuch-sgb/ "null"))
    ergeben. Eine Besonderheit dieser Art von Dienstleistungen ist es,
    dass diese in dem Moment, wenn sie angeboten werden, bereits
    verbraucht werden, weil hier Produktion und Konsumption
    gewissermaßen zusammenfallen. Soziale personenbezogene
    Dienstleistungen können nur schwer standardisiert werden. Anders als
    bei einem Werkstück, was man in eine Maschine einspannt und
    ausmessen kann, sind hier professionelle Normen, Haltungen und
    Ansprüche gemeint, die wie Dienstleistung angeboten werden.

-   Schließlich sind soziale Organisationen dadurch gekennzeichnet, dass
    sie Ehrenamtliche und Freiwillige in die Erfüllung ihrer
    verschiedenen Sachziele einsetzen, was in erwerbsorientierten
    Organisationen in der Regel nicht der Fall ist.

## Herausforderungen in der Sozialwirtschaft {#herausforderungen-sozialwirtschaft}

### Ausgangspunkt {#sozialwirtschaft-ausgangspunkt}

Träger und Einrichtungen in der Sozialwirtschaft müssen stärker
ökonomische Fragen beachten und sich auch am marktwirtschaftlichen
Wettbewerb ausrichten.

Es gibt eine Betätigung auf sozialen Märkten, darüber hinaus ist ein
weiteres, immer noch sehr spezielles Kennzeichen für den Bereich der
Sozialwirtschaft aber auch die Finanzierung. In der Sozialwirtschaft
haben wir es mit einer Vielzahl von Monopolanbietern zu tun. Aus
sozialrechtlicher Perspektive werden diese auch als Leistungsträger
bezeichnet, die gewissermaßen die Leistungen refinanzieren und auch die
notwendigen finanziellen Mittel zur Verfügung stellen. Es ist aber immer
eine Bewerbung notwendig oder die Leistungen müssen beantragt werden --
gegebenenfalls muss auch eine Leistungsvergütung berechnet und
vertraglich geregelt werden (meistens durch Entgeltverträge).
Sozialunternehmen sind daher in hohem Maß abhängig von den
Leistungsträgern und man kann hier größtenteils von einem Monopolmarkt
sprechen.

Als Konsequenz ergibt sich die Notwendigkeit, sich stärker mit
Managementkompetenzen auseinanderzusetzen. In Ihrer Ausbildung lernen
Sie genau deswegen auch verschiedene Grundlagen des Managements, weil
diese notwendig sind, um zukünftig in der Einrichtungsleitung zu
arbeiten bzw. um einen guten Job zu verrichten. Wirtschaftliche
Grundkenntnisse gehören genauso zum Berufsbild wie die
sozialpädagogische Professionalität.

### Hybrid-Funktionen des Sozialmanagements und des Managements in der Sozialwirtschaft {#sozialwirtschat-hybriditaet}

Es gilt immer, einen Fokus auf die Ressourcen zu legen, d. h. es ist
stets auf einen effektiven und effizienten Einsatz von Ressourcen zu
achten. Fragen der Finanzierung, der Investitionsrechnung, des
Controllings und verschiedener anderer Aspekte dieser Hard Facts müssen
berücksichtigt werden.

Um Einrichtungen der Sozialwirtschaft überhaupt betreiben zu können,
gilt es, sich mit der Akquise unterschiedlicher Finanzierungsquellen zu
beschäftigen. Insbesondere in der Sozialwirtschaft existieren
unterschiedliche Finanzierungsquellen und auch verschiedene Quellen
jenseits der öffentlichen Mittel, privaten Mittel oder Spenden. Solche
Einnahmen müssen erst einmal akquiriert werden und zudem gilt es,
gleichzeitig noch den Blick zu öffnen für die Mitarbeiter\*innen der
Einrichtung, die unter enormen Stress und enormen Belastungen ihre
Dienste erbringen. Darüber hinaus muss auch auf die Personalentwicklung
geachtet werden. Den Mitarbeiter\*innen müssen Möglichkeiten für
Weiterbildung und für Karriereentwicklung geboten werden. All das sind
die besonderen Kennzeichen und Herausforderungen in der
Sozialwirtschaft.

Die Sozialwirtschaft ist durch Hybridität gekennzeichnet. Das bringt
besondere Herausforderungen in der Umsetzung des Managements sozialer
Einrichtungen mit sich. Damit ist gemeint -- und hier sei auf die Grafik
von @Whoerle2007 in dem Buch von Volker
@Brinkmann2010 hingewiesen --, dass das
Sozialmanagement hier in die Mitte des Aktionsfeldes gestellt werden
kann und man überlegen sollte, welche anderen Bereiche noch zu beachten
sind (vgl. [Abb. 1.5](#figure15)).

![Abb. 1.5: Hybrid‐Funktionen des Sozialmanagements nach @Arnold2022b in Anlehnung an @Whoerle2007 zit. n. @Brinkmann2010 [S. 25]](images/figure15.png){#figure15}

Wenn man den äußeren Kreis in der [Abb. 1.5](#figure15)
betrachtet, lassen sich eine Reihe von Fachdisziplinen ausfindig machen,
die im Sozialmanagement eine Rolle spielen: u. a. Volkswirtschaftslehre,
Betriebswirtschaftslehre, Public Management. In diesen Disziplinen
stellt man sich die Frage, was denn an Wirtschaftlichkeitserwägungen in
der Gestaltung von sozialen Organisationen beachtet werden soll. Darüber
hinaus müssen auch soziale, politische, rechtliche und
verwaltungsbezogene Grundlagen beachtet werden. Zusätzlich braucht es
fundiertes Wissen aus den Sozialwissenschaften: Es braucht
sozialwissenschaftliche Grundlagen wie z. B. aus der Arbeits- und
Organisationspsychologie, um zu verstehen, wie Personalentwicklung,
Personalführung, Organisationsentwicklung und dergleichen gestaltet
werden können.

Natürlich hat die Disziplin der Sozialen Arbeit darüber hinaus eine
maßgebliche Bedeutung für die Fragestellung: Wie können wir auf der
einen Seite die Professionalität und das Qualitätsverständnis der
Sozialen Arbeit und auf der anderen Seite die ökonomischen
Rahmenbedingungen zusammenführen, sodass sich dies nicht gegenseitig
ausschließt, sondern wie zwei Zahnräder, die ineinandergreifen,
zusammengeführt werden?

Die Herausforderung, die sich für die Sozialwirtschaft, also für
Sozialunternehmen ergeben, sind mindestens zweiteilig. Auf der einen
Seite kann man von Multirationalität, auf der anderen Seite von Hybrid
sprechen. Was ist mit diesen Konzepten gemeint? Darauf soll im Folgenden
näher eingegangen werden.

### Multirationalität und Hybridität {#multirationalitt-und-hybriditaet}

#### Multirationalität {#sozialwirtschat-multirationalitaet}

Multirationalität[^1_einfuehrung-3] ist ein Begriff, der insbesondere
vom Autorenteam @Schedler2013multirationales geprägt wurde, die sich mit der Frage
auseinandergesetzt haben, wie die verschiedenen Rationalitäten, mit
anderen Worten die verschiedenen Ansprüche, Zielstellungen, Wünsche
sowie Interessen, die innerhalb und außerhalb einer Organisation
existieren, zusammengebracht werden können. Sie meinen, dass dauerhaft
und zeitgleich immer mehrere dieser Rationalitäten und Logiken
existieren und es dabei durchaus auch zu Widersprüchen kommen kann in
einer Organisation. All das gilt es zu „managen", in den Blick zu nehmen
und sozusagen als Motivation für die Zusammenarbeit aufzufassen.

[^1_einfuehrung-3]: Ein Einführungsvideo gibt es an dieser Stelle:
    <https://www.youtube.com/watch?v=L_Mf-tNNFJc>

Zum Beispiel gibt es verschiedene Fachsprachen in der Einrichtung, d. h.
bei professionellem Zusammenarbeiten gibt es unterschiedliche
Stakeholder-Interessen. Dies sind die Interessen der Mitarbeitenden, die
Sie vertreten, die der Leitung und auch die der Klient\*innen.

Es sind noch Rahmenbedingungen der Politik und Ökonomie zu beachten. All
das sind unterschiedliche Perspektiven, die immer gleichzeitig
betrachtet werden müssen, wenn es um die Aufgabenkoordination und die
Lösung von Problemen im Arbeitsalltag geht.

#### Hybridität {#hybriditaet}

Neben der Multirationalität gibt es noch ein anderes Prinzip, nämlich
das der Hybridität. Dieses geht stärker auf die Autoren @Evers2010 zurück. Der Begriff
Hybridität kommt aus den Kulturwissenschaften und meint, dass Dinge, die
miteinander zusammengeführt werden, ineinanderfließen und dass es zu
Überschneidungen kommt. Im Kontext der Sozialwirtschaft geht es dabei um
den Einfluss unterschiedlicher, wechselseitig bedingender Werte und
Logiken, die aber nicht nur innerhalb einer Organisation existieren,
sondern auch zwischen den verschiedenen Sektoren der Gesellschaft
vorliegen können. Mit Sektoren der Gesellschaft ist gemeint, dass es
einerseits soziale Leistungen im sozialen Markt gibt und gleichzeitig
auch der öffentliche Bereich mitgedacht werden muss. Also der
Kostenträger bzw. die öffentlichen Einrichtungen, die die angebotenen
personenbezogenen sozialen Dienstleistungen finanzieren, sind
einzubeziehen. Darüber hinaus kann es auch noch andere gesellschaftliche
Interessen geben, nämlich wie die Leistungen angeboten werden und wer
die Bedürftigen bzw. Anspruchsgruppen sind. Es sind darüber hinaus auch
die rechtlichen Rahmenbedingungen zu beachten, der Bereich der
Jurisprudenz, und so könnte man diese Beispiele noch ewig weiterführen.

Was hier zu beachten ist, ist, dass mit Hybridität nicht die des
(internen) Organisationsgeschehens betrachtet wird. Vielmehr werden
unter diesem Konzept die verschiedenen Sektoren der Gesellschaft -- also
die Organisationsumwelt -- in den Blick genommen. Ein Beispiel stellt
hier die Gemeinwesenarbeit dar. Diese kann man als eine „Bearbeitung"
und Gestaltung von Hybridität ansehen, weil das Zusammenarbeiten
verschiedenster Organisationen, Personen und Gruppen im Vordergrund
steht, ob dies nun die Stadt, ein freier Träger oder ein Kommunalverband
ist. Hier muss, um ein soziales Problem möglichst von unterschiedlichen
Perspektiven anzugehen, die Hybridität beachtet werden, also die
Zusammenarbeit von unterschiedlichen Sektoren der Gesellschaft
organisiert werden.

#### Konsequenzen {#sozialwirtschat-konsequenzen}

Einerseits sind Ressourcen von Sozialunternehmen aus unterschiedlichen
Quellen zu nutzen, was oben unter dem Stichpunkt Finanzierungsmix
bereits ausgeführt wurde. Zweitens müssen verschiedene
Interessensgruppen miteinander ausgehandelt werden. Im Sinne des
Partizipationsprinzips und der Beteiligung von unterschiedlichen
Interessensgruppen ist es hilfreich, hier auch Selbstvertretungen in
Organisationen zu organisieren.

Darüber hinaus muss man die Formalziele mit den Sachzielen abwägen, d.
h. auf der einen Seite gibt es natürlich eine Gewinnerzielungsabsicht
und am Ende des Jahres muss mindestens plus/minus null erreicht werden.
Gleichzeitig muss aber auch der ideelle Auftrag, die Vision und der
Unternehmenszweck umgesetzt und erreicht werden (z. B. Betreuungs-,
Beratungs- und Bildungsleistungen).

Damit ist gemeint, dass Organisationen nach innen und nach außen
vertreten werden müssen und sich eine Organisationsidentität entwickelt:
Wofür stehen wir? Was ist unser Auftrag? Wer ist unsere Zielgruppe? All
diese Fragen müssen im Leitbild geklärt werden. Damit beschäftigen wir
uns noch einmal ausführlicher an späterer Stelle. Beide Konzepte, die
Multirationalität und die Hybridität, gewinnen in der Praxis zunehmend
an Bedeutung, insbesondere in der Abgrenzung zwischen Einrichtungen und
in der Gestaltung der Arbeitsbedingungen selbst.
