---
lightbox: true
editor: 
  markdown: 
    wrap: 72
---

# Managementkonzepte {#managementkonzepte}

Nachdem wir uns den betriebswirtschaftlichen und sozialwirtschaftlichen Grundlagen gewidmet und mit dem organisationsbezogenen Management beschäftigt haben, wird im Folgenden auf Managementkonzepte und -ansätze Bezug genommen, die für die Sozialwirtschaftslehre relevant sind. Wenn speziell von Sozialwirtschaft die Rede ist, dann betrachten wir immer noch ein großes Sammelsurium an verschiedenen Aspekten und Teildisziplinen. Seit 1980er Jahren hat sich eine spezielle Managementlehre für die Sozialwirtschaft herausgebildet, die sich mit den betriebswirtschaftlichen Grundlagen für die sozialen Berufe beschäftigt. Einen geschichtlichen Vorläufer stellt beispielsweise die Dienstleistungs-Betriebswirtschaftslehre dar, weil die hauptsächliche Aufgabe sozialer Einrichtungen aus dem Angebot und der Vermarktung von spezifischen Dienstleistungen besteht.

Für die genaue Beschreibung dieser Aufgabe wurde von @Klatetzki2010 der Begriff der „personenbezogenen sozialen Dienstleistungen" geprägt. Im Anschluss an unsere Überlegungen in Kapitel 1 zu den Kennzeichen von sozialen Organisationen werden die folgenden Merkmale hervorgehoben:

-   Diese Art von Dienstleistungen haben einen *immateriellen Charakter*. Wir können die Betreuung, Beratung, Wissensweitergabe    etc. nicht unmittelbar anfassen. Soziale Leistungen stellen sog.    „Erfahrungs- und Vertrauensgüter" dar.

-   Ein zweites Merkmal ist, dass in ihrem Angebot immer die *Produktion und ihre Konsumption* zusammenfallen. Im Moment des Angebots der sozialen Leistung wird diese von der jeweiligen Person, die unterstützt, betreut und beraten wird, entsprechend in Anspruch  genommen. Beide „Akte" der Leistungserbringung fallen zeitlich und   untrennbar voneinander miteinander zusammen. Soziale    personenbezogene Dienstleistungen können nicht gelagert werden, sie  sind vergänglich, benötigen die Mitwirkung der Klient\*innen und    sind zeitlich bzw. örtlich gebunden.

-   Damit eng verbunden ist der Aspekt, dass diese Art von    Dienstleistungen *nur begrenzt *bzw.* schwierig standardisierbar*    ist. D. h. der Erfolg kann nicht ohne Weiteres garantiert werden.    Wir können diese nicht wie ein Werkstück im Herstellungsprozess    hinsichtlich der notwendigen Toleranzen in Form von    Abweichungsanalysen genau vermessen, sondern deren Qualität muss auf andere Weise bestimmt werden. Es hängt viel davon ab, wie    leistungsfähig und kompetent der jeweilige Leistungserbringer ist    und mit wie viel Vertrauen die Sozialleistungen in Anspruch genommen werden. Es sind eher „weiche" Faktoren (*soft skills*), welche über  die letztendliche Qualität bestimmen (z. B. Vertrauen zwischen dem   Leistungserbringer und Leistungsempfänger). Die Entwicklung von    Professionalitätsstandards stellt hierbei einen Weg dar, wobei    gewissermaßen Maximal- oder Mindestkriterien definiert werden, um    sicherzustellen, dass eine bestimmte dokumentierbare Qualität    angeboten wird.

-   Ein weiterer Aspekt sozialer personenbezogener Dienstleistungen ist, dass dabei die „*Defizitorientierung*" in der Sozialen Arbeit,  Pflege, Rehabilitierung, (Kindheits-)Pädagogik überwunden werden    soll. Die Sozialwirtschaft ist eben nicht nur Bedarfswirtschaft, wie @Beck2013 beschreibt, sondern auch eine    Angebotswirtschaft. Wenn wir uns mit sozialwirtschaftlichen Fragen  beschäftigen, dann ist es nicht ausreichend, nur über die    Bedarfsdeckung (Nachfrageorientierung) zu sprechen, sondern auch    über die Generierung von neuen Hilfen wo ggf. noch gar keine Bedarfe bestehen wie z. B. in der Präventionsarbeit oder mit Hilfe von    Empowerment-Ansätzen der Sozialen Arbeit (Angebotsorientierung).

-   Schließlich obliegt die Finanzierung von Aufgaben in der    Sozialwirtschaft im Ganzen oder zumindest teilweise den    *Kostenträgern als Monopolanbietern*. Von Monopol ist hier die Rede, weil die Kostenträger einfach „Herr" über die Sozialleistung sind    und darüber bestimmen, ob eine Leistung abgerechnet und refinanziert werden kann oder nicht und ob etwas, was durchgeführt worden ist,    tatsächlich auch anerkannt wird oder nicht.

Kurz zusammengefasst sind soziale personenbezogene Dienstleistungen letztendlich Vertrauensgüter, die auf die Beziehung zu den Adressat\*innen der Leistungen angewiesen sind. In den folgenden Ausführungen wird es dann darum gehen, wie diese spezifischen Dienstleistungen innerhalb von sozialen Organisationen „gemanagt" werden können. Dafür existieren eine Reihe von Managementkonzepte bzw. -ansätze.

Wenn wir uns im Folgenden mit den verschiedenen Managementkonzepten für die Sozialwirtschaft beschäftigen, handelt es sich in der Regel um *Modelle*. Modelle sind Abbildungen von der Realität. Dabei wird beabsichtigt, eine Reduktion der Wirklichkeit vorzunehmen, um komplexe Zusammenhänge einfacher darzustellen. Diese Modelle beziehen sich auf die Managementpraxis. Und diese Modelle gilt es grundsätzlich zu hinterfragen, d. h. sie zu würdigen und auch kritisch einzuschätzen. Es gilt jeweils, die Vor- und Nachteile (Pro und Contra) abzuwägen und die praktischen Einsatzmöglichkeiten zu prüfen.

Für die Beschreibung oder für die Entwicklung von Konzepten und Ansätzen für das Management sozialer Einrichtungen gibt es unterschiedliche Bereiche, die wir aufgreifen werden. Es sind zwei Bereiche, die hier ausführlicher zur Sprache kommen sollen: die *öffentliche Betriebswirtschaftslehre als spezielle BWL*, die sich insbesondere mit dem Management in öffentlichen Einrichtungen beschäftigt, sowie die *Managementkonzepte von Non-Profit-Organisationen*, die teils in der Praxis, teils in der Theorie entwickelt wurden und von Non-Profit-Organisationen auf soziale Organisationen übertragen werden können.

## Öffentliche Betriebswirtschaftslehre {#oeffentliche-betriebswirtschaftslehre}

### Öffentlich-rechtliche Körperschaften {#oeffentlich-rechtliche-krperschaften}

Die öffentliche Betriebswirtschaftslehre beschäftigt sich, wie der Name schon vermuten lässt, vorwiegend mit Einrichtungen der öffentlichen Hand. Aber nach der Differenzierung von @vogelbusch2017bwl[S. 138] lassen sich verschiedene Einrichtungsformen zuordnen, die an der Erledigung von öffentlichen Aufträgen beteiligt sind:

1.  Zunächst gibt es die *Körperschaften des öffentlichen Rechts*. Dabei handelt sich beispielsweise um Ämter und Behörden (z. B.    Kommunalverwaltungen).

2.  Außerdem beziehen *öffentliche Unternehmen* wie z. B. sog.    Regiebetriebe, Eigenbetriebe und Kommunalunternehmen die Prinzipien der öffentlichen BWL in ihr Handeln mit ein.

3.  Darüber hinaus lassen sich auch *privatrechtlich organisierte   Unternehmen, deren Anteile im Besitz der öffentlichen Hand sind*,   zur öffentlichen BWL zuordnen. Dabei handelt es sich um Unternehmen, die meist als (gemeinnützige) GmbH oder AG (zu 100% oder in    Mehrheitsbesitz) von der öffentlichen Hand betrieben werden. In der Kommune werden hierbei bestimmte Aufgabenstellungen in Form einer   privaten Einrichtung ausgelagert (z. B. kommunale gGmbH).

4.  Schließlich kann es sich um *rein privatrechtliche Unternehmen* handeln, die jetzt auch zur öffentlichen Betriebswirtschaftslehre   gerechnet werden, aber nicht in Besitz der Kommune sind, sondern mit einem bestimmten Auftrag beliehen bzw. beauftragt wurden und durch  die Verwaltung in der Aufgabenumsetzung kontrolliert werden. Dabei  handelt es sich beispielsweise um freie Träger der Kinder- und    Jugendhilfe, der Diakonie oder Caritas sowie anderer    Wohlfahrtsverbände.

Diese Unternehmen zeichnen sich durch die Besonderheit aus, dass die öffentliche Hand im Regelfall die Ziele für die Leistungserstellung vorgibt. Für die konkrete Umsetzung und Leistungserbringung sind dann die darauf spezialisierten Sozialunternehmen, die freien Träger, verantwortlich. Und es muss darauf geachtet werden, dass die Prinzipien der Wirtschaftlichkeit und Sparsamkeit bei der Auftragserledigung umgesetzt werden sowie öffentlich-rechtliche Rahmenbedingungen (z. B. Tarifrecht, Vergaberecht) beachtet werden. Dazu sind alle hier genannten Einrichtungen verpflichtet.

### Bürokratiemodell {#buerokratiemodell}

Im Folgenden werden drei bekannte Modelle der öffentlichen Betriebswirtschaftslehre vorgestellt [vgl. im Folgenden @vogelbusch2017bwl, S. 138-143]: das Bürokratiemodell, das [Neue Steuerungsmodell (NSM)](https://wirtschaftslexikon.gabler.de/definition/neues-steuerungsmodell-nsm-41327 "null") und das Corporate Governance-Modell. Das Bürokratiemodell ist eng mit der klassischen Managementschule -- genauer der bürokratischen Schule -- und dem Soziologien Max Weber verbunden. Erste Entwicklungen stammen bereits aus dem 17. Jahrhundert. Weber hatte die Vorstellung von einer Organisation als ein Strukturgebilde, in dem es ganz klare Hierarchien gibt und alle Aufgaben durch eine funktionale Arbeitsteilung organisiert sind. Das Modell hat eine starke Input-Orientierung, was heißt, dass wenn wir neue Aufgaben hinzubekommen, dafür neue Ressourcen geschaffen bzw. Stellen eingerichtet werden müssen. Das Modell setzt voraus, dass in der Einrichtung eine professionelle Fach- und Amtssprache entwickelt ist. Beamte fungieren in diesem Modell als Entscheidungsträger. Beispiele für Bürokratiemodell sind z. B. Ministerien, kommunale Verwaltungen. Kritisch einzuschätzen ist dabei, dass hier ein Idealtyp von Verwaltung betrachtet wird. Es gibt jedoch noch andere Faktoren, die Einfluss auf Bürokratieorganisationen haben. Organisationen wachsen auch unabhängig davon, dass neue Aufgaben entstehen, was zu einer Überbürokratisierung und Ineffizienz von Strukturen und Prozessen führen kann. Es fehlt in dem Modell auch die Sicht auf das Systemumfeld und den Wettbewerb mit anderen Einrichtungen in der gleichen Kommune oder im Landkreis.

### Neues Steuerungsmodell (NSM)

Neben dem Bürokratiemodell gibt es noch das Neue Steuerungsmodell, das Anfang der 1990er vom Arbeitskreis *K*[*ommunalen Gemeinschaftsstelle für Verwaltungsvereinfachung*](https://de.wikipedia.org/wiki/Kommunale_Gemeinschaftsstelle_f%C3%BCr_Verwaltungsmanagement "null")* (heute: Verwaltungsmanagement; KGSt)* u. a. entwickelt wurde. Das Ziel war, das alte Bürokratiemodell durch ein neues zeitgemäßes Modell zu ersetzen, was stärker ergebnisorientiert funktioniert und die verschiedenen Nachteile kompensiert. Mittlerweile sind viele der kommunalen Behörden und Ämter bundesweit entsprechend dieses Modells organisiert. Das Modell soll eine Wettbewerbsorientierung ermöglichen. Wettbewerb heißt hier, dass beispielsweise, wenn öffentliche Leistungen ausgeschrieben werden, es auch öffentliche Ausschreibungen und Vergabeverfahren geben soll. Dabei wird das Ziel verfolgt, dass derjenige, der das beste Angebot macht und einen vertretbaren Preis aufruft und die geforderte Qualität erbringt, zum Zuge kommen soll. Durch diesen Wettbewerb werden die öffentlichen Mittel, so zumindest in der Theorie, effizienter vergeben. Führungsprozesse sollen in öffentlichen Einrichtungen dezentral organisiert werden, sodass Entscheidungen schneller und im Sinne des Subsidiaritätsprinzips an der geforderten Stelle getroffen werden. Außerdem benötigt jede öffentliche Einrichtung ein strategisches Management und Controlling wie in jedem Privatunternehmen auch. Die Budgetierung erfolgt nach dem Prinzip der doppelten Buchführung, wobei die Einnahmen- und Ausgabenseite einander gegenübergestellt werden. Das Kontraktmanagement (Vertragsmanagement) sorgt dafür, dass Verträge und Bescheide ordnungsgemäß ausgestellt worden sind und regelmäßig hinsichtlich der Umsetzung überprüft werden (Auftragscontrolling). Mit anderen Worten wird in diesem Modell zwischen der öffentlichen Einrichtung und dem freien Träger bzw. Leistungserbringer ein Auftraggeber-Auftragnehmer-Verhältnis generiert, das aus einem Wettbewerb um öffentliche Dienstleistungen entstanden ist. Das Modell hatte schnell viel Zuspruch gefunden, da die Verwaltung nicht mehr nur inputorientiert, sondern auch outputorientiert arbeiten muss. Gleichzeitig hat sich aber ein neues und anderes Problem ergeben. In der Kritik an diesem Modell wird immer von einer „Ökonomisierung des Sozialen" gesprochen. Damit ist gemeint, dass soziale Dienstleistungen in einem betriebswirtschaftlichen Sinne bewertet werden, was nicht unbedingt förderlich ist für die Qualität der Leistungen. Obschon es sich immer noch um Hilfen am Menschen handelt, und durch die Hintertür gewissermaßen Wirtschaftlichkeits- und Sparsamkeitsgrundsätze dazu führen, dass nicht alle Leistungen finanziert werden können. Ebenso dominiert Binnenperspektive, d. h. dass die öffentliche Einrichtung stets über die Finanzierung und Verwendung öffentlicher Mittel entscheidet. Dies wurde bereits weiter oben mit der Marktmacht der Leistungsträger angesprochen (Monopolanbieter).

### Corporate Governance Modell

In den 2000er Jahren hat sich schließlich das Corporate Governance Modell entwickelt. Es wurde versucht, das Neue Steuerungsmodell weiterzuentwickeln und zu reformieren, indem sich auf verschiedene Grundprinzipien, die Good-Governance-Prinzipien, bezogen wird, also wie öffentliche Träger gestaltet und geleitet werden sollen. Die Sichtweise auf Organisationen ist netzwerk- und lernorientiert. D. h. Ressourcen in und außerhalb der Organisation können einbezogen werden. Zu diesen Prinzipien gehören beispielsweise die Beteiligungsorientierung (z. B. Arbeitnehmervertretungen), die Gewaltenteilung zwischen operationaler Geschäftsführung und kontrollierendem Aufsichtsrat und dass Problemlösungsprozesse sich bei komplexen Herausforderungen in der Regel besser durch (einrichtungsübergreifende) Kooperation und weniger durch Kontrakte verwirklichen lassen. Kritisiert wurde an diesem Modell, dass die Good-Governance-Prinzipien nur schwer operationalisiert werden können. Das Modell gibt keine konkreten Schritte vor, um diese Prinzipien umzusetzen. Problematisch könnte außerdem sein, dass sich viele Einrichtungen zu den genannten Prinzipien bekennen können, aber keine klare Kontrollinstanz für die Einhaltung der Governance Prinzipien existiert bzw. verschiedene Prinzipien auch interpretationsbedürftig sind. In den letzten Jahren wurden daher sog. Kodizes entwickelt, wie z. B. der Good Governance Kodex, der eine Liste von Prinzipien beinhaltet. Die Umsetzung eines Kodex obliegt immer einer Selbstverpflichtung.

### Abgrenzung zum Public Management

Abschließend ist noch auf den Begriff des Public Management einzugehen und von der öffentlichen Betriebswirtschaftslehre abzugrenzen [vgl. im Folgenden @vogelbusch2017bwl, S. 143]. Die öffentliche Betriebswirtschaftslehre beschäftigt sich mit der Frage, wie öffentliche Aufträge am besten organisiert und umgesetzt werden können. Dabei kommen auf öffentliche Unternehmen bezogene, input- oder outputorientierte betriebswirtschaftliche Instrumente und Ansätze zum Einsatz. Davon abzugrenzen ist das sog. Public Management, wo es darum geht, den politischen Meinungsbildungsprozess einzubeziehen und zu steuern. Dieser Ansatz beruft sich auf die Grundlagen der Finanzwissenschaften und beabsichtigt ebenfalls eine Steuerung von öffentlichen Körperschaften. Das Public Management wird beispielsweise an den Verwaltungshochschulen gelehrt und verfolgt die Frage, wie eine öffentliche Einrichtung optimal organisiert werden kann. Natürlich gibt es durch das neue Steuerungsmodell, was wir aus der öffentlichen Betriebswirtschaftslehre kennen, solide Grundlagen. Ergänzend werden dabei noch Entscheidungsorgane (z. B. Stadtrat, Landtag, Kreistag) und die Ausschussarbeit im Rahmen von politischen Meinungsbildungsprozessen (z. B. Finanzausschuss, Kinder- und Jugendhilfeausschuss) einbezogen. Ähnlich wie beim Good Governance Modell gibt es beim Public Management ebenso eine Outcome- und Impactorientierung. Damit ist gemeint, dass verschiedene weitere Wirkungen und Effekte der Leistungserbringung auf die Zielgruppe im Speziellen sowie das Gemeinwesen im Allgemeinen betrachtet werden. Mithin finden damit auch eine Evaluierung und Wirkungsüberprüfung von öffentlichen Leistungen statt.

## Allgemeinbetriebswirtschaftliche Modelle der St. Galler Management Schule(n) {#allgemeinbetriebswirtschaftliche-modelle-der-st-galler-management-schulen}

### Überblick {#berblick}

Im Folgenden wird es darum gehen, wie allgemeinbetriebswirtschaftliche Konzepte und Modelle im Management sozialer Organisationen eingesetzt werden können. Die Ausführungen richten sich auf die Anwendung bei freien Trägern der Wohlfahrtspflege und auch bei konfessionellen Trägern der Diakonie oder Caritas. Übertragen lassen sich diese Modelle aber auch auf Non-Profit-Organisationen wie z. B. Stiftungen oder gegebenenfalls kommunale Einrichtungen. Die Modelle der St. Galler Management Schulen sind so bedeutsam, dass man diese auch im Bereich der Non-Profit-Managementlehre kennen und erwähnen muss. Im Grund handelt es sich um vier Generationen:

1.  Das *St. Galler Management-Modell der ersten Generation* (1972-1979) geht auf Hans Ulrich und Walter Krieg zurück, die ein integratives Managementmodell entworfen haben, in dem alle wichtigen Managementfunktionen zusammengeführt sind und eine    systemtheoretische Sichtweise entwickelt wird. In dem Modell sind   auf den äußeren Schalen verschiedene Beteiligte aus Politik,    Wirtschaft und die rechtlichen und ökonomischen Rahmenbedingungen in den Blick genommen. Das Unternehmen wird als ein soziales System    (bestehend aus verschiedenen Subsystemen wie Planung, Organisation  und Kontrolle) betrachtet, welches mit allen Stakeholdern und den  gesellschaftlichen Themen und Aufträgen vernetzt ist.

2.  Das *St. Galler Management-Modell der zweiten Generation*    (1991-1999) ist mit dem Namen Knut Bleicher verbunden. Er    präsentiert einen alternativen Entwurf, wobei weniger die Vernetzung des Unternehmens, sondern vielmehr die Entscheidungsstrukturen bzw. Managementebenen innerhalb der Organisation im Vordergrund stehen.  Er unterscheidet dabei zwischen dem normativen, strategischen und operativen Management. Auch Bleicher betont eine ganzheitliche und  integrative Sicht auf das Management, wobei gesellschaftliche    Veränderungsprozesse (u. a. wirtschaftliche, rechtliche und    natürliche Rahmenbedingungen) ebenso mit aufgenommen werden (vgl.  ausführlicher weiter unten).

3.  Die *dritte Generation des St. Galler Management-Modells*    (2002-2010), entwickelt von Johannes Rüegg-Stürm, die bereits weiter oben eingeführt worden ist, betrachtet das Management auch aus einer holistischen Perspektive, wobei es stärkere Ähnlichkeiten zur ersten als zur zweiten Generation gibt. Stärker herausgearbeitet worden ist hier die Stakeholderperspektive unter Einbeziehung der Systemumwelt. Es handelt sich um ein Modell mit konstruktivistischen als auch    systemtheoretischen Aspekten. Im Zentrum steht das Unternehmen,    welches Prozesse, Strukturen, Strategiebildung, Organisationskultur und Organisationsentwicklungsaufgaben organisieren muss. Die    konstruktivistische Perspektive kommt durch die Einbeziehung der    verschiedenen Sichtweisen der Stakeholder als auch durch die    Interaktionsthemen (u. a. Werte, Erwartungen, Normen, Ressourcen)   zum Tragen. Das Modell ist sehr generalistisch und lässt sich leicht auf unterschiedliche Typen von Organisationen übertragen.

4.  Schließlich existiert seit einigen Jahren die *vierte Generation des St. Galler Management-Modells* (seit 2010), entwickelt von Johannes Rüegg-Stürm und Simon Grand. Es handelt sich um eine    Weiterentwicklung der dritten Generation, wobei die    konstruktivistisch-systemische Sichtweise erhalten geblieben ist.    Neu und stärker herausgearbeitet wurde dabei die Bedeutung des    Managements. Management wird als eine Schlüsselkategorie eingeführt  und wird nicht als individuelles Handlungsvermögen, sondern als    kollektive Praxis beschrieben. Kollektive Praxis des Managements    heißt in diesem Zusammenhang, dass die Interaktion zwischen den    Menschen innerhalb und außerhalb von Organisationen betrachtet wird. Es wird nach dem „wie" gefragt, wie zwischen den Mitarbeitenden und  der Leitung Prozesse arbeitsteilig organisiert, Absprachen und    Entscheidungen getroffen und Verantwortlichkeiten aufgeteilt werden. Im Gegensatz zu den anderen Modellen wird demnach Management als    eine Praxis verstanden.

Kurz zusammengefasst geht es bei allen diesen Modellgenerationen um eine Beschreibung des Lebens von und in Organisationen sowie die verschiedenen Aufgaben und Funktionen, die arbeitsteilig organisiert werden müssen. Die unterschiedlichen Modellversionen lassen sich mehr oder weniger auf unterschiedliche Typen von Organisationen übertragen, Non-Profit-Organisationen (z. B. Sozialwirtschaft, Bildungsbereich, Kulturbereich, Gewerkschaften, Arbeitgeberverbände) wie auch auf gewerbliche Unternehmen.

### St. Galler Management Modell der zweiten Generation {#st-galler-management-modell-der-zweiten-generation}

Hierbei handelt es sich um ein Dreiebenenmodell, in dem zwischen der normativen, strategischen und operativen Ebene unterschieden wird. Auf oberster Ebene, dem *normativen Management*, werden die grundsätzliche Unternehmensphilosophie, Ziele und Strategien sowie der Zweck der Einrichtung festgelegt. In der Satzung werden beispielsweise verbindliche Aufgabenstellungen, stimmberechtige Organe, rechtsverbindliche Vertretungen, die Unternehmensstruktur, Rechtsform, Beteiligungsverhältnisse u.v.m. dargestellt, woraus sich später auf strategischer Ebene die Zielstellungen und das Leitbild, Führungsgrundsätze und die Konzeption einer Einrichtung ableiten lassen. Auf normativer Ebene muss sich das Top-Management mit der Unternehmensverfassung und Unternehmenspolitik beschäftigen. Eine besondere Aufgabe der Leitungskräfte ist die Gestaltung der Organisationskultur. Auf der *strategischen Managementebene* finden dannPlanungsprozesse für die jeweilige Wirtschaftsperiode oder über längere Planungszeiträume (z. B. Jahres- oder Mehrjahrespläne) statt. Mithin müssen die Strategien und Zielsetzungen der Unternehmung quantitativ und qualitativ hergeleitet, umgesetzt und überprüft werden. Auf der strategischen Ebene geht es mit anderen Worten also um die Organisation konkreter Programme. Mit Programmen ist beispielsweise gemeint, dass bestimmte Aufgaben umgesetzt werden (im Sozialunternehmen sind das z. B. Beratung, Betreuung etc.). Diese müssen einerseits strukturell hinsichtlich der Organisationsstrukturen und Managementsysteme strukturiert werden und andererseits ist eine Klärung von Problemen oder Konflikten notwendig. Auf der untersten Ebene, dem *operativen Management*, werden alle konkreten Geschäftsprozesse organisiert und umgesetzt (dazu gehören u. a. Auftragsmanagement, Führungsprozesse, Qualitätssicherung). Auf der operativen Managementebene müssen die alltäglichen Geschäftsprozesse, Kooperationen und die Koordination von Arbeitsaufträgen organisiert werden [vgl. [Abb. 7.1](#figure71) nach @bleicher1999konzept, S. 77, 82].

![Abb. 7.1: Das Konzept integriertes Management im St. Galler Managementmodell der zweiten Generation [@bleicher1999konzept, S. 77, 82]](images/figure71.png){width=75% #figure71}

Im Modell erfolgt zusätzlich eine horizontale und vertikale Integration: Wie in der Abbildung zu sehen ist, geht das Modell von einer Koordination zwischen Strukturbildung, Prozessumsetzung und Verhalten der Mitarbeitenden zur Gestaltung der Zusammenarbeit aus (horizontale Integration) als auch von einer hierarchisch organisierten Top-Down-Strategie (vertikale Integration). Wie der Pfeil im unteren Teil der Grafik zeigt, ist die Abstimmung zwischen den Managementebenen grundsätzlich in einen Prozess der Unternehmensentwicklung einbettet. Es wird von einer Veränderlichkeit und Dynamik ausgegangen und Anpassungen an die jeweils veränderten Rahmenbedingungen sind an der Tagesordnung.

Alle drei Ebenen helfen uns dabei, die verschiedenen Aufgaben im Alltag von Organisationen besser zu strukturieren, Verantwortlichkeiten zu definieren und die Zusammenarbeit zu koordinieren. Kurz zusammengefasst geht es auf normativer Ebene darum: Warum tun wir die Dinge, die wir tun? Auf strategischer Ebene geht es um die Frage: An welchen konkreten Zielsetzungen richten wir unsere Arbeit aus? Und auf operativer Ebene geht es darum: Welche Aufträge haben wir heute zu erledigen, die am Ende der geplanten Wirtschaftsperiode dahingehend überprüft werden müssen, ob die gesetzten Ziele erreicht worden sind und ob wir dem Unternehmenszweck besser gerecht geworden sind?

### St. Galler Management Modell der dritten Generation {#st-galler-management-modell-der-dritten-generation}

Da die dritte Generation des St. Galler Management-Modells bereits weiter oben ausführlich beschrieben wurde, soll an dieser Stelle nur ein kurzer Überblick gegeben werden. In diesem Modell gibt es zunächst die äußeren Umweltsphären Gesellschaft, Natur, Technologie und Wirtschaft. Darüber hinaus wird sich auf den inneren Sphären, den Interaktionsthemen, über Ressourcen, Werte, Anliegen und Interessen ausgetauscht. Beide Aspekte gehören zur Systemumwelt. Auf den äußeren Schalen sind die Stakeholder angesiedelt, die in Interaktion zwischen der Systemumwelt und der Organisation stehen. Dazu zählen unterschiedliche Akteure, Gruppen und Personen. Im Zentrum des Modells steht die Unternehmung mit den verschiedenen Prozessstrukturen und Ordnungsmomenten (Strategien, Strukturen und Kultur). Die Organisation befindet sich in einem ständigen Entwicklungsprozess (Pfeilspitzen) im Rahmen von entweder Erneuerungs- oder Optimierungsprozessen (erste und zweite Ordnung) [vgl. [Abb. 7.2](#figure72) nach @Ruegg-Sturm2003-ga].

![Abb. 7.2: Grundkategorien des SGMM [@Ruegg-Sturm2003-ga, S. 22],
Quelle: <https://de.wikipedia.org/wiki/Datei:SGMM2.jpg> (CC Public
Domain)](images/figure72.jpeg){width=75% #figure72}

Das gesamte Modell ist relativ übersichtlich gestaltet und gibt einen Orientierungsrahmen vor, wie das organisationsbezogene Management umgesetzt werden kann. Es stellt eine Ressource bzw. Rahmenplan dafür dar, worauf im Management zu achten ist. Nachteilhaft in der Darstellung könnte *erstens* sein, dass die einzelnen Managementaufgaben nicht explizit beschrieben werden. *Zweitens* wird in diesem Modell nicht explizit das Personalmanagement, Personalentwicklungsprozesse, Personalführungsprozesse oder Personalmotivation betont. All diese Aspekte spielen bei der Zusammenarbeit in Organisationen eine wichtige Rolle. Dies ist in dem Sinne kein blinder Fleck, aber diese Aspekte sind im Modell noch nicht intensiv genug mitgedacht. Sie lassen sich aber integrieren, wenn man das Personalmanagement zu den Managementprozessen hinzuzählt. Nichtdestotrotz ist die Personal- und Organisationsentwicklung heutzutage untrennbar miteinander verbunden und das muss in den allgemeinen Management-Modellen mitberücksichtigt werden. Im Vergleich zur vierten Generation fehlt in diesem Modell *drittens* noch die integrative Sichtweise von Management als kollektive Praxis. Bereits in der ersten Generation ist in den äußeren Schalen eine Stakeholder-Sichtweise bereits integriert, nur dass dort das Unternehmen noch nicht so differenziert dargestellt wird wie in der dritten Generation. *Viertens* lässt sich die zweite Generation nur teilweise auf der prozessualen Ebene erkennen, wenn zwischen Managementprozessen (strategische Ebene) und Geschäfts- und Unterstützungsprozessen (operative Ebene) unterschieden wird. Mit Geschäftsprozessen sind die Alltagsaufgaben (z. B. Gruppendienste, Betreuungs- und Beratungsaufgaben) gemeint. Die Unterstützungsprozesse beinhalten alltägliche Aufgaben unterstützende Dienste wie z. B. Essensversorgung, Reinigungsdienste und Hausmeisterdienste. Kurz zusammengefasst handelt es sich um ein ganzheitliches Management-Modell, was uns die Organisation aus der Vogelperspektive zu betrachten erlaubt und die Systemumwelt einbezieht.

## Non-Profit-Modelle

### Freiburger Management-Modell für Non-Profit-Organisationen {#freiburger-management-modell-fr-non-profit-organisationen}

Das Freiburger Management-Modell wurde vorrangig im Rahmen von Lehrenden in einem Masterstudiengang für Non-Profit-Management an der Universität Freiburg entwickelt und ist sehr an die Praxis angelehnt. Anwendbar ist dieses Modell insbesondere auf gemeinnützige Organisationen, Verbände, Vereine, Stiftungen etc. Es handelt sich um ein systemtheoretisches Management-Modell, wobei einerseits erfolgskritische Einflussfaktoren auf Managemententscheidung betrachtet werden und andererseits die Gestaltung und Umsetzung des Non-Profit-Managements in Organisation im Vordergrund steht [vgl. [Abb. 7.3](#figure73) nach @schwarz1999freiburger, S. 34].

![Abb. 7.3: Freiburger Management-Modell [nach @schwarz1999freiburger, S. 34]](images/figure73.png){#figure73}

Es wird visualisiert, welche Funktionsbereiche innerhalb einer gemeinnützigen Organisation von Bedeutung sind. Zum besseren Verständnis kann man sich als Hintergrundfolie eine *Stiftung als Non-Profit-Organisation* vorstellen, die unter Verwendung der Erträge ihres Vermögens (Kapitalstock) die Begünstigten hinsichtlich eines festgelegten Zwecks unterstützt bzw. fördert. Das Besondere von Stiftungen ist, dass diese meist Aufgaben- und Zielstellungen verfolgen, die keine private oder staatliche Organisation in dieser Form erfüllen kann. Sie stellen mithin eine Ergänzung zur Verfolgung verschiedener gesellschaftlicher Aufgaben dar und stärken die Zivilgesellschaft. Mit dem Modell lassen sich sehr gut die Zweckverfolgung einer Non-Profit-Organisation und die Nutzenstiftung bei den Begünstigten nachverfolgen.

Das Modell vereint drei prinzipielle Zielsetzungen (sog. „Orientierungen"), zu denen die Marketingorientierung, Zukunfts- und Zielorientierung sowie Effizienz- und Effektivitätsorientierung gehören. Das gesamte Management von Non-Profit-Organisationen soll auf diese drei Perspektiven ausgerichtet werden, sodass sowohl *erfolgs- als auch qualitätskritische Aspekte* fokussiert werden können. Die Perspektive der Zukunfts- und Zielorientierung betont die strategische Perspektive, die Effektivität und Effizienzorientierung schaut auf die verfügbare und zu entwickelnden Ressourcen und die Marketingorientierung weist darauf hin, dass alles organisationale Handeln auf die Bedürfnisse der Zielgruppe(n), Nutzer\*innen der Leistungen, allgemein auf die Stakeholder und Interessensgruppen der Einrichtung ausgerichtet werden muss. Letztlich wird bei der *Marketingorientierung* danach gefragt, wie ein konsequentes Stakeholdermanagement umgesetzt werden kann. Marketing bedeutet hier nicht einfach nur die Umsetzung der Öffentlichkeitsarbeit, sondern es geht vielmehr darum, eine konsequente Kund\*innen- und Klient\*innensicht einzunehmen (verschiedentlich auch als Customer-Relationship-Management bezeichnet). Dabei ist danach zu fragen, welche Dienstleistungen genau angeboten werden, welche Angebote wie an die Adressaten gebracht werden, welcher Nutzen gestiftet werden soll und welche  Wirkungen erzielt werden sollen. Mit anderen Worten soll eine konsequent systematische Sichtweise auf das Marketing eingenommen werden. Eine Gestaltung der notwendigen Strukturen und Prozesse zwischen dem Innen und Außen der Organisation sowie für die verschiedenen Stakeholder verfolgt die Aufgabe der *Zukunfts- und Zielorientierung*. Hierbei geht es um die Frage, welche (Teil-)Aufgaben in unserer Einrichtung organisiert werden müssen. Mit anderen Worten handelt es sich hierbei um das „Systemmanagement" zur strategischen Steuerung der Einrichtung und von Entscheidungsprozessen, wobei solche Fragen im Vordergrund stehen wie z. B. wie müssen unsere Einrichtung und auch das Zusammenspiel mit dem Systemumfeld organisieren sollen, um dem Einrichtungszweck bzw. grundlegenden Aufgaben nachzukommen bzw. gerecht zu werden (vgl. Marketingorientierung oben). Zu den grundlegenden Aufgaben einer Organisation zählen u. a. das Planungswesen, das Controlling, das Personalmanagement, das Qualitätsmanagement. Neben der Marketing- und der Systemperspektive gibt es noch die Ressourcenperspektive, was in dem Modell mit der *Effektivität- und Effizienzorientierung* überschrieben wird. Hierbei geht es um die Gewährleistung von Planungsprozessen, notwendiger Struktur und verfügbarer (Finanz-)Mittel zum Betrieb der Einrichtung. Prozessbeschreibungen und Organigramme müssen erstellt  und/oder ein Qualitätsmanagementhandbuch geschrieben werden, um, wie oben bereits betont, dem Auftrag der Einrichtung gerecht zu werden. Es geht um die Erfüllung der gesetzten strategischen Zielsetzungen mit Hilfe der zur Verfügung stehenden materiellen, personalen, finanziellen und anderen Ressourcen. Die Ressourceneinsatz sollte effizient und effektiv gestaltet werden. Ebenso muss danach gefragt werden, welche Wirkungen wir erzielt haben, gegenüber der Zielgruppe, bezogen auf die Organisation, im Stadtteil bzw. allgemein für das Gemeinwohl. Letztgenannte Sichtweise geht über die (finanztechnische) Gewinnermittlung am Ende des Wirtschaftsjahres weit hinaus. Aus Perspektive einer Stiftung müssen wir uns am Ende des Jahres u. a. die Fragen stellen, welche Förderungen ermöglicht wurden und welche gesellschaftlichen Veränderungsprozesse im Kleinen wie im Großen angeregt wurden.

### Darmstädter Management-Modell {#darmstdter-management-modell}

Ebenfalls aus der Non-Profit-Managementlehre stammt das Darmstädter Management-Modell, welches stärker Bezug zum Sozialmanagement bzw. dem Management von sozialen Organisationen nimmt. Dass das Modell aus einem pädagogischen Kontext stammt, lässt sich anhand seiner Bestandteile schnell erkennen, die auf konkrete Wissens- und Kompetenzbereiche, über die eine Führungskraft im Management einer sozialen Organisation verfügen sollte, hinweist.

Das Modell (vgl. [Abb. 7.4](#figure74)) geht davon aus, dass sich die Sozialwirtschaft in einem ständigen dynamischen Wandel befindet und Sozialbetriebe sich häufig in einem sich kontinuierlich verändernden Umfeld befinden. Solche Veränderung können sich aufgrund von Gesetzesänderung, veränderte Klient\*innenbedarfe etc. ergeben [vgl. @frose2005management, S. 387].

![Abb. 7.4: Darmstädter Management-Modell [in Anlehnung an @frose2005management, S. 387]](images/figure74.png){width=75% #figure74}

Außerdem sind soziale Einrichtungen in den letzten Jahren in verschiedenen Bereichen (z. B. Beratungen) damit konfrontiert, dass die mit dem Leistungsträger hart verhandelten Leistungsentgelte häufig nicht ausreichend sind, um alle entstehenden Aufwendungen zur Leistungserbringung zu refinanzieren und sich eines Mix unterschiedlicher Finanzierungsquellen bedienen müssen. Das Modell soll schließlich das ganzheitlich-systemische Denken, Interdisziplinarität und das interprofessionelle Lernen fördern. Dabei wird darauf geachtet, dass einerseits die sozialarbeiterischen Kontexte und Bedingungen sowie Hintergründe und Theorien einbezogen, andererseits aber auch die wirtschaftlichen Rahmenbedingungen integriert werden. Zum Grundwissen gehört beispielsweise Wissen über die Organisationsentwicklung, Institutionenökonomik (Analyse der Wechselwirkungen von Wirtschaft und gesellschaftlichen Institutionen, wie z. B. Entscheidungsprozesse, Auftraggeber-Auftragnehmer-Verhältnisse) sowie Betriebs- und Volkswirtschaftslehre und rechtliche Grundlagen.

Im äußeren Kreis des Modells finden sich die Hauptthemen, mit denen man sich im Sozialmanagement-Studium beschäftigen sollte. Anders formuliert handelt es sich um die Fähigkeiten und Kompetenzen, die relevant für eine Führungskraft in sozialen Einrichtungen sind. Unten links steht das Thema, die *Persönlichkeit der Leistungskraft* und die Reflexion des eigenen Leitungsstils. Oben steht die *(Praxis-)Organisation* mit den verschiedenen Funktionsbereichen sowie Organisationsentwicklung. Rechts stehen *Wissenschaft, Theorieperspektiven und Analysetechniken*. Im Inneren des Kreises befinden sich drei aneinander liegende Dreiecke (flächig betrachtet) bzw. eine Pyramide (räumlich betrachtet). Ausgehend von den Kernthemen in den drei Ecken finden sich drei Teilbereiche (nummeriert). Im ersten Bereich sind Kenntnisse über *Theorien und Praxis des systemischen Managements* abgebildet. Diesem Themenfeld sind Grundlagen des Managements und der Organisationsentwicklung sowie Reflexion der Managementpraxis in der Gesellschaft (z. B. ethische Verantwortung und Veränderungen in der Organisation und im Umfeld) zugeordnet. Im zweiten Teilbereich finden sich die *sozialwissenschaftlichen Grundlagen*, wozu u. a. das Gesellschafts- und Steuerrecht, die Reflexion von Markt und Gesellschaft (= Wahrnehmung des gesellschaftlichen Auftrags durch soziale Einrichtungen), betriebswirtschaftliche Grundlagen für die Soziale Arbeit, Arbeitsrecht und Forschungsmethoden gehören. Grundsätzlich sind in diesem Teilbereich die interdisziplinären Grundlagen der Sozial-, Rechts- und Gesellschaftswissenschaften zu finden. Im dritten Teilbereich sind die *Führungskompetenzen für das strategische Management* von Einrichtungen abgebildet, wie z. B. Strategieplanung und -überprüfung, das Verfolgen von internationalen Entwicklungen (z. B. Migrations- und Flüchtlingshilfe sowie damit verbundene Herausforderungen) sowie kulturelle und politische Entwicklungen und Netzwerkarbeit.

Im Modell werden alle vorgenannten Kompetenz- und Wissensbereiche abgebildet, nach denen entsprechend die Führungskräfte im Darmstädter Studiengang an der Evangelischen Hochschule in Darmstadt ausgebildet werden. Ähnlich wie beim St. Galler Management-Modell geht es auch im Darmstädter Management-Modell um wesentliche Grundlagen, Arbeitsfelder und Funktionsbereiche des Managements in der Sozialwirtschaft. Eine Spezialität des Modells ist, dass hier vordergründig das Kompetenzprofil von einer idealtypischen Führungskraft betrachtet wird.

### Bielefelder Diakonie-Management-Modell

Das Bielefelder Management-Modell kann sowohl in die Non-Profit-Managementlehre als auch in die Diakoniewissenschaften eingeordnet werden. Beide Disziplinen besitzen Anknüpfungspunkte in der Beschäftigung mit Konzepten und Ansätzen zur Führung und zum Management von Non-Profit-Organisationen. Die Diakoniewissenschaften beziehen sich im Allgemeinen auch auf die betriebswirtschaftlichen Grundlagen für Einrichtungen in konfessioneller Trägerschaft. Das Bielefelder Modell knüpft unmittelbar am St. Galler Management-Modell der zweiten Generation, wie in [Abb. 7.5](#figure75) in den drei Ebenen normatives, strategisches und operatives Management leicht zu erkennen ist. Auf der normativen Ebene geht es um die Ordnung der Unternehmenspolitik, also die Festlegung des Zwecks der Einrichtung, der Aufgabenfelder und Leistungsbereiche. Auf der strategischen Ebene geht es darum, diese Grundsätze und Prinzipien in einen geeigneten Planungsprozess zu überführen, Ziele zu setzen und Strategien zu formulieren. Von Belang ist dabei die Erarbeitung und Überprüfung von Vorgaben für den jeweiligen Planungszeitraum (z. B. sechs Monate, ein oder mehrere Jahre). Und auf der operativen Ebene geht es um die konkrete Unternehmensorganisation und die Umsetzung der Managementaufgaben, die sich im Alltag stellen [vgl. @lohmann1997].

![Abb. 7.5: Bielefelder Diakonie-Management-Modell: Dimensionen [@lohmann1997, S. 172]](images/figure75.png){width=75% #figure75}

Diese drei Ebenen werden schließlich von der theologischen Sinnmitte (links) und der theologischen Effizienz (rechts) flankiert. Mit *theologischer Sinnmitte* ist gemeint, dass alle theologischen Fragestellungen, die sich durch Entscheidungsprozesse im Management tagtäglich ergeben, genauer als wirtschaftsethische Fragestellungen zu reflektieren sind. Mit anderen Worten gibt es immer eine zweite Komponente, die bei Entscheidungen und der Umsetzung von Aufgaben mitgedacht werden muss, nämlich die wirtschaftsethische Reflexion des eigenen ökonomischen Handelns, was z. B. in ethischen Fallbesprechung umgesetzt werden kann. Reflektiert werden sollte nach dieser Ansicht, wie mit Verantwortung umgegangen worden ist, wie Lösung für Dilemmasituationen gefunden werden können und wie mit den Mitarbeitenden umgegangen wurde. Mithin wird hervorgehoben, dass diese ethische Reflexionsfähigkeit eine wichtige Führungskompetenz darstellt. Unter *theologischer Effizienz* wird verstanden, dass die Effizienzfrage im wirtschaftlichen Handeln erweitert werden muss. Natürlich haben konfessionelle Träger die gleichen ökonomischen Grundlagen und Rahmenbedingungen wie andere soziale Einrichtungen. In diesem Modell erfolgt eine Erweiterung um eine theologische Sichtweise, nach der es immer wieder abzuwägen gilt, ob der diakonische Auftrag der Einrichtung auch erreicht werden konnte oder wie man dem Auftrag zukünftig besser gerecht werden kann. Beide Aspekte, die theologische Sinnmitte und die Effizienz, fungieren allgemein als Reflexionsebene, die im Alltag von konfessionellen Einrichtungen mitgedacht werden muss. Institutionalisiert ist dieses Prinzip in der Praxis beispielsweise dadurch, dass im Vorstand meist mindestens zwei Ressorts verteilt sind: eine kaufmännische Geschäftsführung und im Regelfall zusätzlich noch die theologische Geschäftsführung. Leitungsentscheidungen soll gleichzeitig aus kaufmännischer und theologischer Perspektive abgewogen und nicht gegeneinander ausgespielt werden.

![Abb. 7.6: Bielefelder Diakonie-Management-Modell: Management-Theologie [@lohmann1997, S. 190]](images/figure76.png){width=60% #figure76}

In [Abb. 7.6](#figure76) ist zur Verdeutlichung des Verhältnisses von Management und Theologie eine Grafik abgebildet, die diesen Aspekt noch einmal auf den Punkt bringt. Im Mittelpunkt des Diakoniemanagements stehen -- wie bereits beschrieben -- sowohl theologische als auch betriebswirtschaftliche Fragen, die wie zwei Zahnräder ineinandergreifen müssen, da nur dann die Organisation funktioniert. So sind immer die Beziehungen *Management-Theologie* und *Theologie-Management* zu betrachten. Aus Perspektive der theologischen Sinnmitte wird auf biblische, christliche, religiöse Traditionen und Rituale zurückgegriffen (z. B. gemeinsame Gottesdienste, Seelsorgeangebote für Mitarbeitende). Es sind aber auch die gesellschaftlichen, politischen, ökonomischen und natürlichen Rahmenbedingungen und Ressourcen unter Einbeziehung von Interessen der Stakeholder zu beachten. Alles das hat Einfluss auf die Gestaltung des Managements in der diakonischen Einrichtung und beeinflusst alle Entscheidungen.

Im Rahmen dieses Kapitels wurden viele verschiedene Modelle beschrieben, die ganz unterschiedliche Schwerpunkte setzen. Es gilt immer zu prüfen, wie welche Modelle sich in welchen Kontexten und für welche Einrichtungen anwenden bzw. auf diese übertragen lassen.